# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/ticket.rb.tmpl in the ticket repo.
class Ticket < Formula
  desc "A local-first ticket system for engineers — epics, stories, bugs, requirements, decisions"
  homepage "https://github.com/simonski/ticket"
  version "0.1.954"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_darwin_arm64.tar.gz"
      sha256 "a02179e282ef0624c48e2539876feeecdb720d261b3ec0330246da4183d941be"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_darwin_amd64.tar.gz"
      sha256 "f12a5477cd22dd34fd2bf51520141019857b535ad46f83a9039bc7fe1537c426"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_linux_arm64.tar.gz"
      sha256 "3a5bd7f11e8fb3f77aa2c54a72f5b4e7a2bbb4165158210d7503be09ee8a46d9"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_linux_amd64.tar.gz"
      sha256 "7ab2af7a2de2dbce7c09879645523e729b2b2000f0483dcf3eca38f74c596811"
    end
  end

  def install
    bin.install "tk"
  end

  test do
    assert_match "0.1.954", shell_output("#{bin}/tk version")
  end
end
