# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/ticket.rb.tmpl in the ticket repo.
class Ticket < Formula
  desc "A local-first ticket system for engineers — epics, stories, bugs, requirements, decisions"
  homepage "https://github.com/simonski/ticket"
  version "0.1.954"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_darwin_arm64.tar.gz"
      sha256 "6e6a3d0ed52e0f56a7cb3732d628ff7e84685b1ce4f732a75d4a46177c6b095f"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_darwin_amd64.tar.gz"
      sha256 "a771af524bb2a7a77ba72888df568feead1fe5edaa83e191e0ee1cdb6e22d0ab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_linux_arm64.tar.gz"
      sha256 "20958c9bcfd22b9a9d7fb72e5aa896b3d4863debb9cee0c8da6142c9f29ac8d8"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.954/tk_0.1.954_linux_amd64.tar.gz"
      sha256 "0fd43d92c556141a93164e2ebc7f1cb2a96fd61c3d03b0c00a10b5e35665e460"
    end
  end

  def install
    bin.install "tk"
  end

  test do
    assert_match "0.1.954", shell_output("#{bin}/tk version")
  end
end
