# Generated by `make release-formula` — do not edit by hand.
# Source template: homebrew/ticket.rb.tmpl in the ticket repo.
class Ticket < Formula
  desc "A local-first ticket system for engineers — epics, stories, bugs, requirements, decisions"
  homepage "https://github.com/simonski/ticket"
  version "0.1.847"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.847/tk_0.1.847_darwin_arm64.tar.gz"
      sha256 "c5081916146abe4995b9f10ed0ff483e78c3a83a4097c76787b1efc569a05a38"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.847/tk_0.1.847_darwin_amd64.tar.gz"
      sha256 "7e3b8e439096198ec33bb1e47e4d6917454ec54af09fd6b694f1c6eff4fa7566"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/simonski/ticket/releases/download/v0.1.847/tk_0.1.847_linux_arm64.tar.gz"
      sha256 "b46d8841ec18aa8409605f67896f24957d6ae0576d162b5f0562d80f5ba54c81"
    end

    on_intel do
      url "https://github.com/simonski/ticket/releases/download/v0.1.847/tk_0.1.847_linux_amd64.tar.gz"
      sha256 "d32c8e4e11204b44f74d5d833505a9b2de09717210f733face64f17bf4357c6b"
    end
  end

  def install
    bin.install "tk"
  end

  test do
    assert_match "0.1.847", shell_output("#{bin}/tk version")
  end
end
